sudo: required
services:
  - docker

before_install:
  - docker build -t alwin1423/aldocker -f Dockerfile.dev .

script:
  - docker run -e CI=True alwin1423/aldocker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-299491903488"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
